config/routes.rb
Paint::Application.routes.draw do

  resources :comments


  resources :boards do
    resources :posts, :except=>[:index] do
      collection do
        post :save
        get :doodle
        get :upload
      end
      member do
        get :doodle
      end
    end
  end


  resources :users, :except=>[:index, :destroy]


  resources :topics
  resources :password_resets
  resource :user_sessions

  root :to => 'boards#show'
  match 'logout' => 'user_sessions#destroy', :as => :logout
  match 'login' => 'user_sessions#new', :as => :login
  get 'pages/faq' => 'pages#faq', :as => :faq
  get 'pages/rules' => 'pages#rules', :as => :rules
  get 'pages/privacy' => 'pages#privacy', :as => :privacy_policy
  get 'posts/:slug' => 'posts#show', :as=>:share
  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessor :blank_field
  attr_accessible :ip_address, :message, :username, :blank_field
  validates_presence_of [:post, :user_id, :user_type, :message, :ip_address]
  validates_presence_of :username, :if=>:temp_user?
  validate :username_is_not_taken, :if=>:temp_user?
  validate :no_spam, :if=>:temp_user?
  belongs_to :post
  before_create :notify_users

  def notify_users
    if post.user && post.user.notify_on_new_comments
      if user_id != post.user_id
        Mailer.notify_on_comment(post.user_id, post.id).deliver!
      end
    end
  end

  def temp_user?
    user_type == "TempSession"
  end

  def user
    if user_type == "User"
      User.find_by_id(user_id)
    end
  end

  def creator
    username || user.try(:name) || "Anonymous"
  end

  def username_is_not_taken
    if User.find_by_name(username)
      errors.add :username, "is already taken."
    end
  end


  def no_spam
    if message && message.include?("http")
      errors.add :message, "cannot include URLs."
    end
    if blank_field.present?
      errors.add :blank_field, "must be blank"
    end
  end


end

app/controllers/comments_controller.rb
class CommentsController < InheritedResources::Base
    before_filter :may_edit_comment, :only=>[:edit, :update]
    before_filter :may_delete_comment, :only=>[:destroy]
    def new
      @post = Post.find(params[:post_id])
      @comment = generate_comment(session_obj)
    end

    def create
      @post = Post.find(params[:post_id])
      @comment = generate_comment(session_obj, params[:comment])
      if @comment.save
        flash[:notice] = "Thanks! You just brightened someone's day!"
        redirect_to @comment.post.board
      else
        flash[:error] = @comment.errors.full_messages.first
        render :new
      end
    end

    def update
      @comment = Comment.find(params[:id])
      @post = @comment.post
      if @comment.update_attributes(params[:comment])
        redirect_to @comment.post.board
      else
        flash[:error] = @comment.errors.full_messages.first
        render :edit
      end
    end
private
  def may_edit_comment
    if @comment = Comment.find(params[:id])
      unless (current_user && current_user.may_edit_comment?(@comment))
        flash[:error] = "Please login as a moderator to do that."
        redirect_to new_user_url
      end
    end
  end

  def may_delete_comment
    if @comment = Comment.find(params[:id])
      unless (current_user && current_user.may_delete_comment?(@comment))
        flash[:error] = "Please login as a moderator to do that."
        redirect_to new_user_url
      end
    end
  end


end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
              <div class="comment">
                <figure>
                  <%=render :partial=>"posts/avatar", :locals=>{:user=>comment.user}%>
                  <figcaption><%=comment.creator%></figcaption>
                
                </figure>
                <%=simple_format(comment.message)%>
                <div class="small">
                  <time class="published dt-published" datetime="<%=comment.created_at.strftime("%Y-%m-%d")%>" itemprop="datePublished" pubdate=""><%=distance_of_time_in_words Time.now, comment.created_at%> ago</time>

                  <%if logged_in? && current_user.may_edit_comment?(comment)%>    
                    <%=link_to "Edit", edit_comment_path(comment)%>
                    &bullet; <%= link_to "Delete", comment_path(comment), :method => :delete, :confirm=>"Are you sure you want to delete this comment?" %>

                  <%end%>
                </div>
              </div>

app/views/comments/_form.html.erb
<div class="form-wrapper">
  <div class="form-inner-wrapper">
    <%= form_for(@comment) do |f| %>
      <div class="field-list clear">
        <input type="hidden" name="post_id" value="<%=@comment.post.id%>">
        <div class="form-item field">
          <%= f.label :message, :class=>"title" %><br />
          <%= f.text_area :message, :class=>"field-element", :rows=>nil %>
        </div>
        <%if @comment.temp_user?%>
          <div class="form-item field">
            <%= f.label :username, :class=>"title" %><br />
            <%= f.text_field :username, :class=>"field-element" %>
          </div>
          <div class="form-item field" id="blank-field">
            <%= f.label :blank_field, "Leave this field blank", :class=>"title" %><br />
            <%= f.text_field :blank_field, :class=>"field-element" %>
          </div>          
        <%end%>
          
        <div class="submit-holder">
          <input type="submit" value="<%=@comment.new_record? ? "Reply" : "Update"%>" class="button sqs-system-button sqs-editable-button"> <%=render :partial=>"posts/avatar", :locals=>{:user=>current_user}%>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/comments/edit.html.erb
<%= render 'form' %>

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <tr>
    <th>Message</th>
    <th>Username</th>
    <th>Ip address</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @comments.each do |comment| %>
  <tr>
    <td><%= comment.message %></td>
    <td><%= comment.username %></td>
    <td><%= comment.ip_address %></td>
    <td><%= link_to 'Show', comment %></td>
    <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
    <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<%=render :partial=>"posts/post", :locals=>{:post=>@post}%>

<%= render 'form' %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Message:</b>
  <%= @comment.message %>
</p>

<p>
  <b>Username:</b>
  <%= @comment.username %>
</p>

<p>
  <b>Ip address:</b>
  <%= @comment.ip_address %>
</p>


<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>