config/routes.rb
Paint::Application.routes.draw do

  resources :comments


  resources :boards do
    resources :posts, :except=>[:index] do
      collection do
        post :save
        get :doodle
        get :upload
      end
      member do
        get :doodle
      end
    end
  end


  resources :users, :except=>[:index, :destroy]


  resources :topics
  resources :password_resets
  resource :user_sessions

  root :to => 'boards#show'
  match 'logout' => 'user_sessions#destroy', :as => :logout
  match 'login' => 'user_sessions#new', :as => :login
  get 'pages/faq' => 'pages#faq', :as => :faq
  get 'pages/rules' => 'pages#rules', :as => :rules
  get 'pages/privacy' => 'pages#privacy', :as => :privacy_policy
  get 'posts/:slug' => 'posts#show', :as=>:share
  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :message, :title, :paint_time, :in_progress, :username, :image, :is_upload, :faq_category
  belongs_to :board
  validates_presence_of [:board,:user_id,:user_type]
  validates_presence_of [:title, :message], :unless=>:in_progress?
  #validates_length_of :message, :minimum=>20, :unless=>:in_progress?, :too_short=>"is too short. Write more!"
  validates_presence_of :username, :if=>:temp_user?, :unless=>:in_progress?
  validate :enough_paint_time
  validate :unique_username
  validate :no_spam, :if=>:temp_user?
  before_save :set_slug
  scope :finished, :conditions => {:in_progress => false}
  has_many :comments, :order=>"id asc"
  before_save :notify_users
  after_create :notify_users_on_create

  IMG_PATH = '/posts/:board_id/:id_:style.:ext'
  #.CHI is not an animation file, just layer info
  ANIM_PATH = '/anim/:board_id/:id.chi' 
  PALETTE_PATH = '/palettes/:board_id/:id.aco'

  has_attached_file :image, { :path => ':rails_root/public' +IMG_PATH,
            :url => IMG_PATH,
            :bucket=>Settings.storage_bucket,
          }.merge(Settings.storage_settings)
  has_attached_file :anim, { :path => ':rails_root/public' +ANIM_PATH,
            :url => ANIM_PATH,
            :bucket=>Settings.storage_bucket,
          }.merge(Settings.storage_settings(false))
  has_attached_file :palette, { :path => ':rails_root/public' +PALETTE_PATH,
            :url => PALETTE_PATH,
            :bucket=>Settings.storage_bucket,
          }.merge(Settings.storage_settings(false))

  def notify_users_on_create
    if !in_progress?
      User.notifiable_on_post.each do |temp_user|
        next if temp_user.id == user_id
          Mailer.notify_on_post(temp_user.id, id).deliver!
      end      
    end
  end

  def notify_users
    if !in_progress? && in_progress_changed?
      User.notifiable_on_post.each do |temp_user|
        next if temp_user.id == user_id
          Mailer.notify_on_post(temp_user.id, id).deliver!
      end
    end
  end

  def already_finished?
    id && !in_progress?
  end

  def creator
    username || user.try(:name) || "Anonymous"
  end

  def user
    if user_type == "User"
      User.find_by_id(user_id)
    end
  end


  def temp_user?
    user_type == "TempSession"
  end

  def load_image_url
    return image.url if image.present?
  end

  def load_chibi_file_url
    return anim.url if anim.present?
  end

  def load_swatches_url
    return palette.url if palette.present?
  end

  def copy_to(user)
    return nil unless user
    self.user_id = user.id
    self.user_type = user.class.to_s
    self.save!   
  end

  def set_slug
    if slug.blank? && title.present?
      self.slug = "#{id} #{title}".parameterize
    end
  end

  def self.faq_keys
    {"help"=>"Technical Help", "howto"=>"How to Do Everything", "rules"=>"The Rules and Rule-breaking"}
  end

protected

def helpers
  ActionController::Base.helpers
end

def no_spam
  # if temp_user?
    if message && message.include?("http")
      errors.add :message, "cannot include URLs."
    end
    if title && title.include?("http")
      errors.add :title, "cannot include URLs."
    end
  # end
end

  def enough_paint_time
    if paint_time && !in_progress?
      if paint_time < Settings.min_paint_time
        errors.add :paint_time, "is too short. Click <a href='/boards/#{board_id}/posts/doodle'>doodle</a> and draw some more! (Limit is #{helpers.distance_of_time_in_words(Settings.min_paint_time)})".html_safe
      end
    end
  end

  def unique_username
    if username
      if User.find_by_name(username)
        errors.add :username, "is taken"
      end
    end
  end



 end

app/controllers/posts_controller.rb
class PostsController < InheritedResources::Base
    protect_from_forgery :except => [:save]
    before_filter :get_post, :only=>[:new, :edit, :doodle, :save, :show]
    before_filter :get_board
    before_filter :require_post, :only=>[:new, :edit, :show]
    before_filter :may_edit_post, :only=>[:doodle, :destroy, :edit, :update]

    def show
      @title = @post.title
    end

    #To reach, click "Doodle" or "Continue"
    def doodle
      @paint = {
        :saveUrl => saveUrl,
        :postUrl => postUrl
      }
      if @post
        @paint[:loadImageUrl] = @post.load_image_url
        @paint[:loadChibiFileUrl] = @post.load_chibi_file_url
        @paint[:loadSwatchesUrl] = @post.load_swatches_url
        @paint[:rotation] = @post.rotation
      else
        @paint[:canvasWidth] = params[:width] || Settings.canvas.default_height
        @paint[:canvasHeight] = params[:height] || Settings.canvas.default_width
      end
      render :layout=>nil
    end


    #To reach, click on "Save" in ChickenPaint
    def save #always post
      #TODO: don't let people overwrite others' posts by changing the URL
      @post ||= generate_post(@user, {
        :paint_time=>0, 
        :in_progress=>true})
      #overwrite work in progress
      if params[:started_at] && @post.paint_time.present?
        @post.paint_time += Time.now.to_i - params[:started_at].to_i
      else
        @post.paint_time = nil
      end
      @post.image = params[:picture]
      @post.anim = params[:chibifile]
      @post.palette = params[:swatches]
      @post.rotation = params[:rotation]
      @post.save!
      
      #save and continue drawing option
      render :text=>"CHIBIOK\n" and return
    end


    #to reach, click "Upload" in menu
    def upload
      @active_link = "upload"
      @post = generate_post(session_obj, {:is_upload=>true})
      render :new
    end

    #To reach, click "Upload" then the submit button
    def create
      @active_link = "upload"
      params[:post][:is_upload] = true
      @post = generate_post(session_obj, params[:post])
      if @post.save
        flash[:notice] = "You made a new post!"
        redirect_to board_path(@board)
      else
        flash[:error] = @post.errors.full_messages.first
        render :new
      end
    end

    #To reach, click the submit button when posting art or editing message
    def update
      @active_link = "doodle"
      @post = Post.find(params[:id])
      #mark the post finished and run validations
      @post.in_progress = false
      if @post.update_attributes(params[:post])
        flash[:notice] = "Hooray!"
        redirect_to board_path(@board)
      else
        flash[:error] = @post.errors.full_messages.first
        render :edit
      end
    end


private
    def get_board
      @board = @post.try(:board) || Board.find_by_id(params[:board_id]) || Board.default
    end

    def get_post
      @user = session_obj
      if params[:id]
        @post = Post.find_by_id(params[:id])
      elsif params[:slug]
        @post = Post.find_by_slug(params[:slug])
      else
        @post = @user.work_in_progress
      end
    end
    def require_post
      unless @post
        flash[:error] = "That post was deleted."
        redirect_to board_path(@board)
      end
    end

  def saveUrl
    params = {:started_at=>Time.now.to_i}
    if @post
      if @post.is_upload?
        #i.e. continuing a static image
        params.except! :started_at
      end
      if @post.id && params[:new_slot].blank?
        #i.e. editing a finished post
        params[:id]=@post.id
      end
    end
    return save_board_posts_path(params)
  end

  def postUrl
    if @post && params[:new_slot].blank?
      return edit_post_path(@post)
    end
    return new_post_path

  end
private
  def may_edit_post
    if @post
      unless session_obj.may_edit_post?(@post)
        flash[:error] = "Please login as a moderator to do that."
        redirect_to new_user_url
      end
    end
  end
end

app/views/posts/_avatar.html.erb
<%if user%>
    <%if user.avatar.present?%>
        <%=image_tag user.avatar.url(:small), :class=>"avatar"%>
    <%end%>
<%end%>

app/views/posts/_canvas_size.html.erb
<%=render :partial=>'common/cool_popup_start', :locals=>{:table_class=>"canvas-size-form hidden", :title=>"How big?",:right=>""}%>
    <%= form_tag doodle_path, :method=>:get %>
        <div style="text-align:center;">
          <div class="center-me">How big?</div>
          <%=text_field_tag :width, Settings.canvas.default_width, :size=>3, :style=>"display:table-cell"%> x
          <%=text_field_tag :height, Settings.canvas.default_height, :size=>3, :style=>"display:table-cell"%>
          <input type="submit" class="button sqs-system-button sqs-editable-button" value="Start">
        </div>
    </form>
<%=render :partial=>'common/cool_popup_end'%>

app/views/posts/_faq.html.erb
    <div><b><%=post.title%></b></div>
    <div>
      <%=post.message%>
     
        
        <%if logged_in? && current_user.admin?%>    
         <div class="small">
          <%=link_to "Edit", edit_post_path(post)%>
          
            &bullet; <%= link_to "Delete", post_path(post), :method => :delete, :confirm=>"Are you sure you want to delete this entire post?" %>
         </div>
        <%end%>
     

      </div>

app/views/posts/_form.html.erb
<%if @post.id && @post.image.present?%>
  <%=render :partial=>"image", :locals=>{:src=>@post.image.url}%>
<%end%>
<div class="form-wrapper">
  <div class="form-inner-wrapper">
    <%= form_for [@board, @post] do |f| %>
      <div class="field-list clear">
        <div class="form-item field">
          <%= f.label :title, :class=>"title" %>
          <%= f.text_field :title, :class=>"field-element" %>
        </div>
        <div class="form-item field">
          <%= f.label :message, :class=>"title" %>
          <%= f.text_area :message, :class=>"field-element", :rows=>nil %>
        </div>
        <%if @post.temp_user?%>
          <div class="form-item field">
            <%= f.label :username, "Your Name", :class=>"title" %>
            <%= f.text_field :username, :class=>"field-element" %>
          </div>
        <%end%>
        <%if @active_link=="upload"%>
          <div class="form-item field">
            <%=f.label :image, "Image (optional)", :class=>"title"%>
            <%=f.file_field :image, :class=>"field-element"%>
          </div>
        <%end%>
        <%if @post.new_record? && @post.is_upload?%>
          <div class="option"><label><input id="i-made-this" type="checkbox" value="1" name="uploaded_art"> I made this image</label></div>
        <%end%>
        <%if @board.faq?%>
          <div class="form-item field">
            <select name="post[faq_category]">
              <%Post.faq_keys.keys.each do |k|%>
                <option><%=k%></option>
              <%end%>
            </select>
          </div>          
        <%end%>
        <div class="submit-holder">
          <input type="submit" value="<%=@post.already_finished? ? "Update" : "Post"%>" class="button sqs-system-button sqs-editable-button">  <%=render :partial=>"posts/avatar", :locals=>{:user=>current_user}%>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/_image.html.erb
<!--<div class="sqs-block image-block sqs-block-image">
    <div class="sqs-block-content">
        <div class="image-block-outer-wrapper layout-caption-below">
            <div style="max-width:800.0px;" class="intrinsic">
                <div class="image-block-wrapper has-aspect-ratio" style="padding-bottom:75.0%;">
                    <img class="thumb-image loaded" style="top: 0%; left: 0; position: absolute;  " src="<%=src%>?format=750w">
                </div>
                
            
            </div>
    
        </div>
    </div>
</div> -->
<div class="image-holder">
  <img src="<%=src%>">
</div>

app/views/posts/_post.html.erb
  <article class="hentry post-type-text article-index-4">
    <!--POST HEADER-->
      <header>
        <h1 class="entry-title" itemprop="headline">
            <%=link_to post.title, share_path(post.slug)%>
          
        </h1>
        <div class="meta">
          <div style="display:none"><time class="published dt-published" datetime="<%=post.created_at.strftime("%Y-%m-%d")%>" itemprop="datePublished" pubdate=""><%=distance_of_time_in_words Time.now, post.created_at%> ago</time></div>
          <%if post.paint_time && post.paint_time > 0%>
            <span class=""><i>Paint time: <%=distance_of_time_in_words post.paint_time%></i></span>
            <span class="author"><b><%=post.creator%></b></span>
          <%else%>
            <span class="author">posted by <b><%=post.creator%></b></span>
          <%end%>
          
        </div>
      </header>

      <%if post.image.present?%>
        <%=render :partial=>"posts/image",:locals=>{:src=>post.image.url}%>
      <%end%>
      <div class="body entry-content" style="text-align:center">
        <div style="display:inline-block; text-align:left">

          <figure>
            <%=render :partial=>"posts/avatar", :locals=>{:user=>post.user}%>
            <figcaption><%=post.creator%></figcaption>
          </figure>
          <%=simple_format(post.message)%>
          <div class="small">
            <time class="published dt-published" datetime="<%=post.created_at.strftime("%Y-%m-%d")%>" itemprop="datePublished" pubdate=""><%=distance_of_time_in_words Time.now, post.created_at%> ago</time>
            <%if logged_in? && current_user.may_edit_post?(post)%> 
              <%=link_to "Edit", edit_post_path(post)%>
              <%if post.image.present? && current_user.may_continue_post?(post)%>
                &bullet; <%=link_to "Continue",doodle_path(post)%>
              <%end%>
                &bullet; <%= link_to "Delete", post_path(post), :method => :delete, :confirm=>"Are you sure you want to delete this entire post?" %>
                <%if current_user.mgt?%>
                 <br/><i><%=post.ip_address%></i>
                <%end%>
            <%end%>
          </div>

         
            <!-- note: post.comments breaks when comments get deleted. -->
            <%post.reload.comments.each do |comment|%>
              <%=render :partial=>"comments/comment", :locals=>{:comment=>comment}%>
            <%end%>
        

        </div>
      </div>

    <%unless @comment%><!-- no need to put the link to comment if they're already doing it -->
    <footer class="clear">
      <div class="meta">
        <div class="second meta-row">
          <span class="sqs-simple-like">
            <%=link_to "Reply", new_comment_path(:post_id=>post)%> &bullet; <%=link_to "Share", "#", :class=>"share", "data-share"=>"share#{post.id}"%>
          </span>


        </div>

      </div>
    </footer>
    <%end%>
  
    <%=render :partial=>'common/cool_popup_start', :locals=>{:table_class=>"share-form hidden", :id=>"share#{post.id}"}%>
      <div class="center-me">Where to?</div>
      <div class="center-me">
      <%if post.image.present?%>
        <%=image_tag post.image.url(:medium), :class=>"cute"%>
      <%end%>
      →
      <%["twitter","facebook","tumblr"].each do |soc|%>
        <%=link_to image_tag("social-#{soc}.png", :class=>"icon"), Settings.share[soc].gsub("{url}", "http://#{Settings.host}#{share_path(post.slug)}").gsub("{title}",post.title).gsub("{desc}", post.message)%>
      <%end%>
      </div>
      
    <%=render :partial=>'common/cool_popup_end'%>

  </article>

app/views/posts/doodle.html.erb
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title><%=Settings.title%></title>

<script type="text/javascript">
	/* Check for native pointer event support before PEP adds its polyfill */
	if (window.PointerEvent) {
		window.hasNativePointerEvents = true;
	}
</script>

<script src="/paint/lib/raf.js"></script>
<script src="/paint/lib/es6-promise.min.js"></script>
<script src="/paint/lib/jquery-2.2.1.min.js"></script>
<script src="/paint/lib/pep.min.js"></script>
<script src="/paint/lib/pako.min.js"></script>
<script src="/paint/lib/keymaster.js"></script>
<script src="/paint/lib/EventEmitter.min.js"></script>
<script src="/paint/lib/FileSaver.min.js"></script>
<script src="/paint/lib/bootstrap.min.js"></script>

<script src="/paint/resources/js/chickenpaint.js"></script>
<script>
  $(document).ready(function() {
    new ChickenPaint({
        uiElem: document.getElementById("chickenpaint-parent"),
        <%@paint.each do |key, value|%>
          <%next if value.nil?%>
          <%=key%>: <%=value.is_a?(String) ? "'#{value}'".html_safe : value%>,
        <%end%>
        allowSave: true,
        allowMultipleSends: true,
        resourcesRoot: "/paint/resources/",

    });
});
</script>

<link rel="stylesheet" type="text/css" href="/paint/resources/css/chickenpaint.css">
</head>
<body>
	<div id="chickenpaint-parent"></div>
    <p></p>
    
</body>
</html>

app/views/posts/edit.html.erb
<%= render 'form' %>

app/views/posts/new.html.erb
<%= render 'form' %>

app/views/posts/show.html.erb
<div class="article-list hfeed">
  <%=render :partial=>"posts/post", :locals=>{:post=>@post}%>
</div>