config/routes.rb
Paint::Application.routes.draw do

  resources :comments


  resources :boards do
    resources :posts, :except=>[:index] do
      collection do
        post :save
        get :doodle
        get :upload
      end
      member do
        get :doodle
      end
    end
  end


  resources :users, :except=>[:index, :destroy]


  resources :topics
  resources :password_resets
  resource :user_sessions

  root :to => 'boards#show'
  match 'logout' => 'user_sessions#destroy', :as => :logout
  match 'login' => 'user_sessions#new', :as => :login
  get 'pages/faq' => 'pages#faq', :as => :faq
  get 'pages/rules' => 'pages#rules', :as => :rules
  get 'pages/privacy' => 'pages#privacy', :as => :privacy_policy
  get 'posts/:slug' => 'posts#show', :as=>:share
  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
end

app/views/common/_cool_popup_end.html.erb
     </div>
    </div>
  </div>
</div>

app/views/common/_cool_popup_start.html.erb
<%id ||= ""%>
<div class="cool-popup <%=table_class%>" style="width: 250px; position: absolute;" id="<%=id%>">
  <div class="body">
    <div class="form-wrapper">
      <div class="form-inner-wrapper">

app/views/common/_menu.html.erb
      <ul>
        <li class="page-collection <%="active-link" if @active_link=="home"%>">
            <%=link_to "Community.", root_url%>
        </li>
        <li class="page-collection <%="active-link" if @active_link == "doodle"%>">
            <%=link_to "Doodle a pic.", doodle_path, :class=>"doodle-link "+set_canvas_size_class%>
        </li>
          <li class="page-collection <%="active-link" if @active_link == "upload"%>">
              <%=link_to "ask a question.", upload_board_posts_path(@board || Board.default)%>
          </li>
        <%if logged_in?%>
          <li class="page-collection <%="active-link" if @active_link == "edit_account"%>">
               <%=link_to "Profile.", edit_user_path(current_user)%>
          </li>
        <%else%>
          <li class="page-collection">  
             <%=link_to "Login.", login_path, :class=>"loginable"%>
          </li>
          <li class="page-collection <%="active-link" if @active_link == "new_account"%>">
              <%=link_to "New Account.", new_user_path%>
          </li>
        <%end%>
        <li class="page-collection <%="active-link" if @active_link == "faq"%>">
            <%=link_to "FAQ.", faq_path%>
        </li>
      </ul>