config/routes.rb
Paint::Application.routes.draw do

  resources :comments


  resources :boards do
    resources :posts, :except=>[:index] do
      collection do
        post :save
        get :doodle
        get :upload
      end
      member do
        get :doodle
      end
    end
  end


  resources :users, :except=>[:index, :destroy]


  resources :topics
  resources :password_resets
  resource :user_sessions

  root :to => 'boards#show'
  match 'logout' => 'user_sessions#destroy', :as => :logout
  match 'login' => 'user_sessions#new', :as => :login
  get 'pages/faq' => 'pages#faq', :as => :faq
  get 'pages/rules' => 'pages#rules', :as => :rules
  get 'pages/privacy' => 'pages#privacy', :as => :privacy_policy
  get 'posts/:slug' => 'posts#show', :as=>:share
  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html xmlns:og="http://opengraphprotocol.org/schema/" xmlns:fb="http://www.facebook.com/2008/fbml" xmlns:website="http://ogp.me/ns/website" lang="en-US" itemscope="" itemtype="http://schema.org/WebPage" class="yui3-js-enabled js flexbox canvas canvastext webgl no-touch hashchange history draganddrop rgba hsla multiplebgs backgroundsize borderimage borderradius boxshadow textshadow opacity cssanimations csscolumns cssgradients cssreflections csstransforms no-csstransforms3d csstransitions video audio svg inlinesvg svgclippaths wf-proximanova-i1-active wf-proximanova-i3-active wf-proximanova-i4-active wf-proximanova-i5-active wf-proximanova-i6-active wf-proximanova-i7-active wf-proximanova-i8-active wf-proximanova-i9-active wf-proximanova-n1-active wf-proximanova-n3-active wf-proximanova-n4-active wf-proximanova-n5-active wf-proximanova-n6-active wf-proximanova-n7-active wf-proximanova-n8-active wf-proximanova-n9-active wf-active" style="">
  <div id="yui3-css-stamp" style="position: absolute !important; visibility: hidden !important"></div>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="initial-scale=1">
    <title><%=Settings.title%> - <%=action_name%> <%=controller_name.classify.downcase%>.</title>
    <link rel="shortcut icon" type="image/x-icon" href="http://<%=Settings.host%>/favicon.ico">
    <link rel="canonical" href="http://<%=Settings.host%>">
    <meta property="og:site_name" content="<%=Settings.title%>">
    <meta property="og:url" content="http://<%=request.path%>">
    <meta property="og:type" content="website">
    <meta name="twitter:url" content="http://<%=request.path%>">
    <meta name="twitter:card" content="summary">
    <%if @post && @post.already_finished?%>
      <meta property="og:title" content="<%=@post.title%>">
      <meta itemprop="name" content="<%=Settings.title%>">
      <meta name="twitter:title" content="<%=@post.title%>">
      <meta name="description" content="<%=@post.message%>">
      <%if @post.image%>
        <meta property="og:image" content="<%=@post.image.url%>">
      <%end%>
    <%else%>
      <meta property="og:title" content="<%=Settings.title%>">
      <meta itemprop="name" content="<%=Settings.title%>">
      <meta name="twitter:title" content="<%=Settings.title%>">
      <meta name="description" content="<%=Settings.description%>">
    <%end%>
    


    <link rel="stylesheet" type="text/css" href="/css/site.css">
    <link rel="stylesheet" type="text/css" href="/css/application.css">
    <link href='https://fonts.googleapis.com/css?family=Merriweather:400,700' rel='stylesheet' type='text/css'>
    <script   src="https://code.jquery.com/jquery-2.2.3.js"   integrity="sha256-laXWtGydpwqJ8JA+X9x2miwmaiKhn8tVmOVEigRNtP4="   crossorigin="anonymous"></script>
    <%=javascript_include_tag "jquery_ujs","login","application","popups"%>


  </head>
  <body class="show-products-category-navigation  page-borders-thick canvas-style-normal  header-subtitle-address banner-alignment-center blog-layout-center project-layout-left-sidebar thumbnails-on-open-page-show-all social-icon-style-round  hide-info-footer     hide-article-author product-list-titles-under product-list-alignment-center product-item-size-32-standard  product-gallery-size-11-square product-gallery-auto-crop show-product-price show-product-item-nav product-social-sharing  event-show-past-events event-thumbnails event-thumbnail-size-32-standard event-date-label  event-list-show-cats event-list-date event-list-time event-list-address   event-icalgcal-links  event-excerpts  event-item-back-link     hide-opentable-icons opentable-style-dark newsletter-style-dark small-button-style-solid small-button-shape-square medium-button-style-solid medium-button-shape-square large-button-style-solid large-button-shape-square button-style-outline button-corner-style-square tweak-product-quick-view-button-style-floating tweak-product-quick-view-button-position-bottom tweak-product-quick-view-lightbox-excerpt-display-truncate tweak-product-quick-view-lightbox-show-arrows tweak-product-quick-view-lightbox-show-close-button tweak-product-quick-view-lightbox-controls-weight-light native-currency-code-usd collection-type-blog collection-layout-default collection-565e0a46e4b09a621bfc4187 view-list mobile-style-available logo-image" id="collection-565e0a46e4b09a621bfc4187">

    <div id="canvas" style="margin-top:20px;">
        <div class="alert-holder">
          <% flash.each do |key, value| %>
            <div class="alert alert-dismissable alert-<%=key%>">
              <button  class="close" data-dismiss="alert" type="button"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
              <%=raw(value)%>
            </div>
          <%end%>
        </div>
        <%if post = session_obj.work_in_progress%>
          <%if !(post == @post)%><!-- i.e. they are already posting it -->
            <div class="alert alert-dismissable alert-info">
              <button  class="close" data-dismiss="alert" type="button"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
              <%=image_tag post.image.url(:medium), :class=>"cute"%>
              <%=link_to "Post this image", edit_post_path(post)%> &nbsp; 
              <%=link_to "Continue this image", doodle_path(post)%> &nbsp; 
              <%= link_to "Delete", post_path(post), :method => :delete, :confirm=>"Are you sure you want to delete this work in progress?" %>
            </div>
          
            <%if !logged_in?%>
              <div class="alert alert-dismissable alert-warning">
                <button  class="close" data-dismiss="alert" type="button"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <strong>Don't lose your work!</strong> &nbsp; <%=link_to "Log in", login_path, :class=>"loginable"%> or <%=link_to "Create an Account", new_user_path%> to transfer your artwork to your account.
              </div>
            <%end%>
          <%end%>
        <%end%>
         
        <div id="mobileNav" class="">
          <div class="wrapper">
            <nav class="main-nav mobileNav">
              <%= render :partial=>"common/menu"%>
            </nav>
          </div>
        </div>
        <div id="mobileMenuLink"><a>Menu</a></div>
        
        <header id="header" class="clear">
          <!--<div id="upper-logo">
            <h1 class="logo" data-content-field="site-title">
              <a href="<%=doodle_path%>" class="<%=set_canvas_size_class%>"><img src="/images/logo.jpg" alt="<%=Settings.host%>"></a>
            </h1>
          </div>-->
          <div class="site-tag-line"></div>

          <div id="lower-logo">
            <h1 class="logo" data-content-field="site-title" data-shrink-original-size="42" style="letter-spacing: 0.0238095em;">
              <a href="<%=doodle_path%>" class="<%=set_canvas_size_class%>"><img src="/images/logo.jpg" alt="<%=Settings.host%>"></a>
            </h1>
          </div>

          <div id="topNav" style="margin-top:20px">
            <nav class="main-nav" data-content-field="navigation">
            <%= render :partial=>"common/menu"%>
            <div class="page-divider"></div>
            </nav>
          </div>
        </header>

        <div class="page-divider top-divider"></div>
        <section id="page" class="clear" role="main" data-content-field="main-content" data-collection-id="565e0a46e4b09a621bfc4187" data-edit-main-image="Banner" style="opacity: 1; min-height: auto;">
          <%=yield%>

        </section>
        <footer id="footer" class="clear">
            <p>Can't think of what to draw? How about... <b><%=Topic.order("RANDOM()").first.try(:name)%></b></p>
          
            <p>
              <%if logged_in?%>
              <%=link_to "logout", logout_path%>
              &bullet;
              <%end%>
              <%=link_to "privacy", privacy_policy_path%>
              &bullet;
              <%=link_to "angelboy", "http://angelboy.com"%>
            </p>
          
          
        </footer>
        <%= render( :partial =>"user_sessions/login_form") if current_user.blank? %>
        <%= render( :partial =>"posts/canvas_size") %>
      </div><!-- end #canvas -->
    </body>
  </html>

app/views/layouts/email.html.erb
<!doctype html>
<html>
<head>
<meta name="viewport" content="width=device-width">
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<style>
/* -------------------------------------
    GLOBAL
------------------------------------- */
* {
  font-family: "Helvetica Neue", "Helvetica", Helvetica, Arial, sans-serif;
  font-size: 100%;
  line-height: 1.6em;
  margin: 0;
  padding: 0;
}

img {
  max-width: 600px;
  width: auto;
}

body {
  -webkit-font-smoothing: antialiased;
  height: 100%;
  -webkit-text-size-adjust: none;
  width: 100% !important;
}


/* -------------------------------------
    ELEMENTS
------------------------------------- */
a {
  color: #348eda;
}

.btn-primary {
  Margin-bottom: 10px;
  width: auto !important;
}

.btn-primary td {
  background-color: #348eda; 
  border-radius: 25px;
  font-family: "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif; 
  font-size: 14px; 
  text-align: center;
  vertical-align: top; 
}

.btn-primary td a {
  background-color: #348eda;
  border: solid 1px #348eda;
  border-radius: 25px;
  border-width: 10px 20px;
  display: inline-block;
  color: #ffffff;
  cursor: pointer;
  font-weight: bold;
  line-height: 2;
  text-decoration: none;
}

.last {
  margin-bottom: 0;
}

.first {
  margin-top: 0;
}

.padding {
  padding: 10px 0;
}


/* -------------------------------------
    BODY
------------------------------------- */
table.body-wrap {
  padding: 20px;
  width: 100%;
}

table.body-wrap .container {
  border: 1px solid #f0f0f0;
}


/* -------------------------------------
    FOOTER
------------------------------------- */
table.footer-wrap {
  clear: both !important;
  width: 100%;  
}

.footer-wrap .container p {
  color: #666666;
  font-size: 12px;
  
}

table.footer-wrap a {
  color: #999999;
}


/* -------------------------------------
    TYPOGRAPHY
------------------------------------- */
h1, 
h2, 
h3 {
  color: #111111;
  font-family: "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif;
  font-weight: 200;
  line-height: 1.2em;
  margin: 40px 0 10px;
}

h1 {
  font-size: 36px;
}
h2 {
  font-size: 28px;
}
h3 {
  font-size: 22px;
}

p, 
ul, 
ol {
  font-size: 14px;
  font-weight: normal;
  margin-bottom: 10px;
}

ul li, 
ol li {
  margin-left: 5px;
  list-style-position: inside;
}

/* ---------------------------------------------------
    RESPONSIVENESS
------------------------------------------------------ */

/* Set a max-width, and make it display as block so it will automatically stretch to that width, but will also shrink down on a phone or something */
.container {
  clear: both !important;
  display: block !important;
  Margin: 0 auto !important;
  max-width: 600px !important;
}

/* Set the padding on the td rather than the div for Outlook compatibility */
.body-wrap .container {
  padding: 20px;
}

/* This should also be a block element, so that it will fill 100% of the .container */
.content {
  display: block;
  margin: 0 auto;
  max-width: 600px;
}

/* Let's make sure tables in the content area are 100% wide */
.content table {
  width: 100%;
}

</style>
</head>

<body bgcolor="#f6f6f6">

<!-- body -->
<table class="body-wrap" bgcolor="#f6f6f6">
  <tr>
    <td></td>
    <td class="container" bgcolor="#FFFFFF">


      <!-- content -->
      <div class="content">
      <table>
        <tr>
          <td>
            <%=yield%>
          </td>
        </tr>
      </table>
      </div>
      <!-- /content -->
      
    </td>
    <td></td>
  </tr>
</table>
<!-- /body -->

<!-- footer -->
<table class="footer-wrap">
  <tr>
    <td></td>
    <td class="container">
      
      <!-- content -->
      <div class="content">
        <table>
          <tr>
            <td align="center">
              <%if @user%>
                <p><a href="<%=edit_user_url(@user)%>"><unsubscribe>Set email preferences</unsubscribe></a>
              <%end%>
              </p>
            </td>
          </tr>
        </table>
      </div>
      <!-- /content -->
      
    </td>
    <td></td>
  </tr>
</table>
<!-- /footer -->

</body>
</html>